name: ditonton
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.3
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.5
  google_fonts: ^3.0.1
  flutter_rating_bar: ^4.0.0
  cached_network_image: ^3.0.0
  get_it: ^7.1.3
  intl: ^0.17.0
  sqflite_sqlcipher: ^2.1.0  
  rxdart: ^0.27.1
  path_provider: ^2.0.2
  firebase_core: ^1.24.0
  firebase_crashlytics: ^2.9.0
  flutter_svg: ^1.1.5
  flutter_bloc: ^8.0.0
  encrypt: ^5.0.1
  readmore: ^2.2.0

dev_dependencies:
  mockito: ^5.0.8
  build_runner: ^2.0.4
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - certificates/

